/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abrirarchivos;
import abrirarchivos.tabla1;
import abrirarchivos.Conexion;
import java.awt.Color;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;

/**
 *
 * @author 24DD018LA
 */
public class formulario extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    tabla1 tabla;
    public formulario() {
        initComponents();
        tabla = new tabla1();
        
        
        setLocationRelativeTo(null);
          lbl_aviso.setVisible(false);
          lbl_aviso1.setVisible(false);
          lbl_aviso2.setVisible(false);
          lbl_aviso4.setVisible(false);
          lbl_aviso3.setVisible(false);
          lbl_aviso6.setVisible(false);
          lbl_aviso7.setVisible(false);
          lbl_aviso5.setVisible(false);
          lbl_aviso9.setVisible(false);
          lbl_aviso8.setVisible(false);
          lbl_aviso11.setVisible(false);
          lbl_aviso10.setVisible(false);
          lbl_aviso13.setVisible(false);
          lbl_aviso12.setVisible(false);
          lbl_aviso15.setVisible(false);
          lbl_aviso14.setVisible(false);
        
                                           
    }
private void limpiar(){
    txt_id_tabla.setText("");
    txt_tarjeta.setText("");
    txt_id_pago.setText("");
    txt_moneda.setText("");
    txt_transaccion.setText("");
    txt_id_banco.setText("");
    txt_identidad.setText("");
    txt_hora.setText("");
    txt_anios.setText("");
    txt_fecha.setText("");
    txt_fecha_nacimiento.setText("");
    txt_telefono.setText("");
    txt_correo.setText("");
    txt_web.setText("");
    txt_monto.setText("");
    txt_id_empleado.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tarjeta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        lbl_id_pago = new javax.swing.JLabel();
        lbl_id_tabla = new javax.swing.JLabel();
        lbl_moneda = new javax.swing.JLabel();
        lbl_transaccion = new javax.swing.JLabel();
        lbl_id_banco = new javax.swing.JLabel();
        lbl_identidad = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        lbl_anios = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        lbl_web = new javax.swing.JLabel();
        lbl_monto = new javax.swing.JLabel();
        lbl_id_empleado = new javax.swing.JLabel();
        txt_id_tabla = new javax.swing.JTextField();
        txt_tarjeta = new javax.swing.JTextField();
        txt_id_pago = new javax.swing.JTextField();
        txt_moneda = new javax.swing.JTextField();
        txt_transaccion = new javax.swing.JTextField();
        txt_id_banco = new javax.swing.JTextField();
        txt_identidad = new javax.swing.JTextField();
        txt_hora = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        txt_anios = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_web = new javax.swing.JTextField();
        txt_monto = new javax.swing.JTextField();
        txt_id_empleado = new javax.swing.JTextField();
        lbl_id_tabla1 = new javax.swing.JLabel();
        lbl_fecha_nacimiento = new javax.swing.JLabel();
        txt_fecha_nacimiento = new javax.swing.JTextField();
        lbl_aviso1 = new javax.swing.JLabel();
        lbl_aviso = new javax.swing.JLabel();
        lbl_aviso2 = new javax.swing.JLabel();
        lbl_aviso4 = new javax.swing.JLabel();
        lbl_aviso3 = new javax.swing.JLabel();
        lbl_aviso6 = new javax.swing.JLabel();
        lbl_aviso7 = new javax.swing.JLabel();
        lbl_aviso5 = new javax.swing.JLabel();
        lbl_aviso9 = new javax.swing.JLabel();
        lbl_aviso8 = new javax.swing.JLabel();
        lbl_aviso11 = new javax.swing.JLabel();
        lbl_aviso10 = new javax.swing.JLabel();
        lbl_aviso13 = new javax.swing.JLabel();
        lbl_aviso12 = new javax.swing.JLabel();
        lbl_aviso15 = new javax.swing.JLabel();
        lbl_aviso14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_confirmar = new javax.swing.JButton();
        jScrollt = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos_tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tarjeta.setText("Tarjeta");

        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbl_id_pago.setText("id_pago");

        lbl_id_tabla.setText("id_tabla");

        lbl_moneda.setText("Moneda");

        lbl_transaccion.setText("Numero Transaccion");

        lbl_id_banco.setText("id_banco");

        lbl_identidad.setText("identidad");

        lbl_hora.setText("Hora ");

        lbl_anios.setText("Años de Experiencia");

        lbl_fecha.setText("Fecha");

        lbl_telefono.setText("Telefono");

        lbl_correo.setText("Correo Electronico");

        lbl_web.setText("Sitio Web");

        lbl_monto.setText("Monto");

        lbl_id_empleado.setText("id Empleado");

        txt_id_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_tablaActionPerformed(evt);
            }
        });

        txt_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tarjetaActionPerformed(evt);
            }
        });

        txt_id_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_pagoActionPerformed(evt);
            }
        });

        txt_moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_monedaActionPerformed(evt);
            }
        });

        txt_anios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_aniosActionPerformed(evt);
            }
        });

        txt_id_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_empleadoActionPerformed(evt);
            }
        });

        lbl_id_tabla1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        lbl_id_tabla1.setText("Validacion de Expresiones Rregulares");

        lbl_fecha_nacimiento.setText("fecha nacimiento");

        lbl_aviso1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso1.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso1.setText("CAMPO VACIO");

        lbl_aviso.setBackground(new java.awt.Color(204, 204, 204));
        lbl_aviso.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso.setText("CAMPO VACIO");
        lbl_aviso.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbl_avisoInputMethodTextChanged(evt);
            }
        });

        lbl_aviso2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso2.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso2.setText("CAMPO VACIO");

        lbl_aviso4.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso4.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso4.setText("CAMPO VACIO");

        lbl_aviso3.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso3.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso3.setText("CAMPO VACIO");

        lbl_aviso6.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso6.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso6.setText("CAMPO VACIO");

        lbl_aviso7.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso7.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso7.setText("CAMPO VACIO");

        lbl_aviso5.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso5.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso5.setText("CAMPO VACIO");

        lbl_aviso9.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso9.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso9.setText("CAMPO VACIO");

        lbl_aviso8.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso8.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso8.setText("CAMPO VACIO");

        lbl_aviso11.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso11.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso11.setText("CAMPO VACIO");

        lbl_aviso10.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso10.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso10.setText("CAMPO VACIO");

        lbl_aviso13.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso13.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso13.setText("CAMPO VACIO");

        lbl_aviso12.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso12.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso12.setText("CAMPO VACIO");

        lbl_aviso15.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso15.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso15.setText("CAMPO VACIO");

        lbl_aviso14.setBackground(new java.awt.Color(255, 255, 255));
        lbl_aviso14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_aviso14.setForeground(new java.awt.Color(204, 0, 0));
        lbl_aviso14.setText("CAMPO VACIO");

        btn_confirmar.setText("CONFIRMAR");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_confirmar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(btn_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrolltMouseClicked(evt);
            }
        });

        datos_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        datos_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datos_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datos_tbl);

        jScrollt.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbl_tarjeta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_tarjeta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_transaccion)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_transaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_aviso4)
                                    .addComponent(lbl_aviso5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_web)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_web))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbl_correo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_aviso7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_aviso6))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_id_banco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_aviso3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_id_empleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_aviso2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_id_pago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_aviso1))))
                    .addComponent(lbl_id_tabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_id_tabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lbl_aviso)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_monto)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_aviso15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_aviso14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_fecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_aviso10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_aviso11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_identidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_aviso8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_anios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_anios, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_aviso9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_moneda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_aviso12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_fecha_nacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_aviso13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollt, javax.swing.GroupLayout.PREFERRED_SIZE, 1187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_id_tabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id_tabla)
                            .addComponent(txt_id_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_aviso2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_id_banco)
                                    .addComponent(txt_id_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_aviso3))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_id_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_id_pago)
                                    .addComponent(lbl_aviso1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tarjeta)
                            .addComponent(txt_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso4)
                            .addComponent(lbl_identidad)
                            .addComponent(txt_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso8))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_transaccion)
                            .addComponent(txt_transaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso5)
                            .addComponent(lbl_anios)
                            .addComponent(txt_anios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_telefono))
                            .addComponent(lbl_aviso14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_monto)
                            .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_fecha)
                            .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_hora)
                            .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso11))
                        .addGap(70, 70, 70)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_moneda)
                            .addComponent(txt_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_fecha_nacimiento)
                            .addComponent(txt_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_correo)
                            .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_aviso6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_web, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_web)
                            .addComponent(lbl_aviso7))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollt, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_tablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_tablaActionPerformed

    private void txt_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tarjetaActionPerformed

    private void txt_id_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_pagoActionPerformed

    private void txt_monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_monedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_monedaActionPerformed

    private void txt_aniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_aniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aniosActionPerformed

    private void txt_id_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_empleadoActionPerformed

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        // TODO add your handling code here:
        int validacion =0;
        String id_tabla = txt_id_tabla.getText().trim();
        String tarjeta = txt_tarjeta.getText().trim();
        String id_pago= txt_id_pago.getText().trim();
         String fecha_nacimiento = txt_fecha_nacimiento.getText().trim();
        String moneda = txt_moneda.getText().trim();
        String transaccion = txt_transaccion.getText().trim();
        String id_banco = txt_id_banco.getText().trim();
        String identidad = txt_identidad.getText().trim();
        String hora = txt_hora.getText().trim();
        String anios = txt_anios.getText().trim();
        String fecha = txt_fecha.getText().trim();
        String telefono = txt_telefono.getText().trim();
        String correo =txt_correo.getText().trim();
        String web = txt_web.getText().trim();
        String monto = txt_monto.getText().trim();
        String id_empleado = txt_id_empleado.getText().trim();
        
        Pattern patron = Pattern.compile("[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]"); //expresion de la tarjeta 
        Matcher coincidir = patron.matcher(tarjeta);
        Pattern patron2 = Pattern.compile("[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9]"); //expresion de la  identidad
        Matcher coincidir2 = patron2.matcher(identidad);
        Pattern patron3 = Pattern.compile("[w][w][w][.]%[.]%"); //expresion deL sitio web
        Matcher coincidir3 = patron3.matcher(web);
        Pattern patron4 = Pattern.compile("[1-9]%[.]%"); //expresion deL monto
        Matcher coincidir4 = patron4.matcher(monto);
        Pattern patron5 = Pattern.compile("[0-9][1][0-5]"); //expresion de años
        Matcher coincidir5 = patron5.matcher(anios);
        Pattern patron6 = Pattern.compile("19[5-9][0-9]-0[1-9]-[0-2][0-9]19[5-9][0-9]-1[0-2]-[0-2][0-9]19[5-9][0-9]-1[0-2]-[0-2][0-9]2000-1[0-2]-[0-2][0-9]"); //expresion de la fecha de nacimiento
        Matcher coincidir6 = patron6.matcher(fecha_nacimiento);
         Pattern patron7 = Pattern.compile("0[0-9]:[0-5][0-9][0-9]:[0-5][0-9]1[0-9]:[0-5][0-9]2[0-3]:[0-5][0-9]"); //expresion de hora
        Matcher coincidir7 = patron7.matcher(hora);
         Pattern patron8 = Pattern.compile("[a-z,0-9,_,-]%@[a-z,0-9,_,-]%.[a-z][a-z]%"); //correo
        Matcher coincidir8 = patron8.matcher(correo);
        Pattern patron9 = Pattern.compile("[a-z,0-9,_,-]%@[a-z,0-9,_,-]%.[a-z][a-z]%"); //expresion de la fecha
        Matcher coincidir9 = patron9.matcher(fecha);
        Pattern patron10 = Pattern.compile("[2-9][1-9][1-9][1-9][0-9][0-9][0-9][0-9]"); //expresion del telefono
        Matcher coincidir10 = patron10.matcher(telefono);
        
        if(txt_id_tabla.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(null,"EL ID TABLA ES INVALIDO");
            lbl_aviso.setVisible(true);
        }else{
            lbl_aviso.setVisible(false); 
        }
         if(txt_id_pago.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(null,"EL ID PAGO NO ES VALIDO");
            lbl_aviso1.setVisible(true);
        }else{
            lbl_aviso1.setVisible(false);
        }
          if(txt_id_banco.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(null,"EL ID BANCO NO ES VALIDO");
            lbl_aviso4.setVisible(true);
        }else{
           lbl_aviso4.setVisible(false); 
        }
            if(txt_moneda.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(null,"LA MONEDA NO ES VALIDA");
            lbl_aviso12.setVisible(true);
        }else{
             lbl_aviso12.setVisible(false);
        }
        
        if(txt_tarjeta.getText().trim().isEmpty() && coincidir.find() == false){
            JOptionPane.showMessageDialog(null,"LA TARJETA NO ES VALIDA");
            lbl_aviso4.setVisible(true);
        }else {
             JOptionPane.showMessageDialog(null,"LA TARJETA ES VALIDA");
               lbl_aviso4.setVisible(false);
        }
        
            if(txt_identidad.getText().trim().isEmpty() && coincidir2.find() == false){
            JOptionPane.showMessageDialog(null,"LA IDENTIDAD NO ES VALIDA");
            lbl_aviso8.setVisible(true);
            }else {
             JOptionPane.showMessageDialog(null,"LA iIDENTIDAD ES VALIDA");
             lbl_aviso8.setVisible(false);
        }
        
        if(txt_web.getText().trim().isEmpty() && coincidir3.find() == false){
            JOptionPane.showMessageDialog(null,"EL SITIO WEB NO ES VALIDO");
            lbl_aviso7.setVisible(true);
        }  else {
             JOptionPane.showMessageDialog(null,"EL SITIO WEB ES VALIDO");
             lbl_aviso7.setVisible(false);
        }
        
        if(txt_monto.getText().trim().isEmpty() && coincidir4.find() == false){
            JOptionPane.showMessageDialog(null,"EL MONTO NO ES VALIDO ");
            lbl_aviso15.setVisible(true);
        }  else {
             JOptionPane.showMessageDialog(null,"EL MONTO ES VALIDO");
             lbl_aviso15.setVisible(false);
        }
         if(txt_anios.getText().trim().isEmpty() && coincidir5.find() == false){
            JOptionPane.showMessageDialog(null,"LOS AÑOS DE EXPERIENCIA NO ES VALIDO");
            lbl_aviso9.setVisible(true);
        }else {
             JOptionPane.showMessageDialog(null,"LOS AÑOS DE EXPERIENCIA ES VALIDO");
             lbl_aviso9.setVisible(false);
        }
         if(txt_fecha_nacimiento.getText().trim().isEmpty() && coincidir6.find() == false){
            JOptionPane.showMessageDialog(null,"LA FECHA DE NACIMIENTO NO ES VALIDA");
            lbl_aviso13.setVisible(true);
        }else {
             JOptionPane.showMessageDialog(null,"LA FECHA DE NACIMIENTO ES VALIDO");
             lbl_aviso13.setVisible(false);
        }
         if(txt_hora.getText().trim().isEmpty() && coincidir7.find() == false){
            JOptionPane.showMessageDialog(null,"LA HORA NO ES VALIDA");
            lbl_aviso11.setVisible(true);
        }else {
             JOptionPane.showMessageDialog(null,"LA HORA ES VALIDA " );
             lbl_aviso11.setVisible(false);
        }
         
         if(txt_correo.getText().trim().isEmpty() && coincidir8.find() == false){
            JOptionPane.showMessageDialog(null,"EL CORREO ELECTRONICO NO ES VALIDO");
            lbl_aviso6.setVisible(true);
        }else {
             JOptionPane.showMessageDialog(null,"EL CORREO ELECTRONICO ES VALIDO");
             lbl_aviso6.setVisible(false);
        }
         if(txt_fecha.getText().trim().isEmpty() && coincidir9.find() == false){
            JOptionPane.showMessageDialog(null,"LA FECHA ACTUAL NO ES VALIDA");
            lbl_aviso10.setVisible(true);
        }else {
             JOptionPane.showMessageDialog(null,"LA FECHA ES VALIDA");
             lbl_aviso10.setVisible(false);
        }
         if(txt_telefono.getText().trim().isEmpty() && coincidir10.find() == false){
            JOptionPane.showMessageDialog(null,"EL TELEFONO NO ES VALIDO");
            lbl_aviso14.setVisible(true);
        }else {
             JOptionPane.showMessageDialog(null,"EL TELEFONO ES VALIDO");
             lbl_aviso14.setVisible(false);
        }
       if(id_tabla.equals("")){
           txt_id_tabla.setBackground(Color.red);
           validacion++;
       }
        if(tarjeta.equals("")){
           txt_tarjeta.setBackground(Color.red);
           validacion++;
       }
         if(id_pago.equals("")){
           txt_id_pago.setBackground(Color.red);
           validacion++;
       }
          if(fecha_nacimiento.equals("")){
           txt_fecha_nacimiento.setBackground(Color.red);
           validacion++;
       }
           if(moneda.equals("")){
           txt_moneda.setBackground(Color.red);
           validacion++;
       }
            if(transaccion.equals("")){
           txt_transaccion.setBackground(Color.red);
           validacion++;
       }
             if(id_banco.equals("")){
           txt_id_banco.setBackground(Color.red);
           validacion++;
       }
              if(identidad.equals("")){
           txt_identidad.setBackground(Color.red);
           validacion++;
       }
               if(hora.equals("")){
           txt_hora.setBackground(Color.red);
           validacion++;
       }
                if(anios.equals("")){
           txt_anios.setBackground(Color.red);
           validacion++;
       }
                 if(fecha.equals("")){
           txt_fecha.setBackground(Color.red);
           validacion++;
       }
                  if(telefono.equals("")){
           txt_telefono.setBackground(Color.red);
           validacion++;
       }
                   if(correo.equals("")){
           txt_correo.setBackground(Color.red);
           validacion++;
       }
                    if(web.equals("")){
           txt_web.setBackground(Color.red);
           validacion++;
       }
                     if(monto.equals("")){
           txt_monto.setBackground(Color.red);
           validacion++;
       }
                      if(id_empleado.equals("")){
           txt_id_empleado.setBackground(Color.red);
           validacion++;
       }
         
    }//GEN-LAST:event_btn_confirmarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
 tabla = new tabla1(Integer.valueOf(txt_id_tabla.getText()), Integer.valueOf(txt_tarjeta.getText()), Integer.valueOf(txt_id_pago.getText()), Integer.valueOf(txt_id_banco.getText()),Integer.valueOf(txt_id_empleado.getText()), Integer.valueOf(txt_anios.getText()), Integer.valueOf( txt_transaccion.getText()),txt_moneda.getText(),txt_fecha_nacimiento.getText(),txt_identidad.getText(),txt_hora.getText(),txt_fecha.getText(),txt_telefono.getText(),txt_correo.getText(),txt_monto.getText(),txt_web.getText() );
 tabla.agregar();
 datos_tbl .setModel(tabla.leer());
// TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void lbl_avisoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbl_avisoInputMethodTextChanged
          // TODO add your handling code here:
    }//GEN-LAST:event_lbl_avisoInputMethodTextChanged

    private void jScrolltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrolltMouseClicked

    }//GEN-LAST:event_jScrolltMouseClicked

    private void datos_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datos_tblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_datos_tblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JTable datos_tbl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollt;
    private javax.swing.JLabel lbl_anios;
    private javax.swing.JLabel lbl_aviso;
    private javax.swing.JLabel lbl_aviso1;
    private javax.swing.JLabel lbl_aviso10;
    private javax.swing.JLabel lbl_aviso11;
    private javax.swing.JLabel lbl_aviso12;
    private javax.swing.JLabel lbl_aviso13;
    private javax.swing.JLabel lbl_aviso14;
    private javax.swing.JLabel lbl_aviso15;
    private javax.swing.JLabel lbl_aviso2;
    private javax.swing.JLabel lbl_aviso3;
    private javax.swing.JLabel lbl_aviso4;
    private javax.swing.JLabel lbl_aviso5;
    private javax.swing.JLabel lbl_aviso6;
    private javax.swing.JLabel lbl_aviso7;
    private javax.swing.JLabel lbl_aviso8;
    private javax.swing.JLabel lbl_aviso9;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_fecha_nacimiento;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_id_banco;
    private javax.swing.JLabel lbl_id_empleado;
    private javax.swing.JLabel lbl_id_pago;
    private javax.swing.JLabel lbl_id_tabla;
    private javax.swing.JLabel lbl_id_tabla1;
    private javax.swing.JLabel lbl_identidad;
    private javax.swing.JLabel lbl_moneda;
    private javax.swing.JLabel lbl_monto;
    private javax.swing.JLabel lbl_tarjeta;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_transaccion;
    private javax.swing.JLabel lbl_web;
    private javax.swing.JTextField txt_anios;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_fecha_nacimiento;
    private javax.swing.JTextField txt_hora;
    private javax.swing.JTextField txt_id_banco;
    private javax.swing.JTextField txt_id_empleado;
    private javax.swing.JTextField txt_id_pago;
    private javax.swing.JTextField txt_id_tabla;
    private javax.swing.JTextField txt_identidad;
    private javax.swing.JTextField txt_moneda;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_tarjeta;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_transaccion;
    private javax.swing.JTextField txt_web;
    // End of variables declaration//GEN-END:variables
}
